---
# Keep the default Vagrant SSH key. It's publicly available and thus
# "insecure", but these VMs aren't for production use and having a well-known
# key allows for easy automation and documentation.
ssh:
  insert_key: false

vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.
  - name: split-master
    hostname: split-master.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-7-x86_64'
      - type: openstack
        volume_boot:
          image: 'centos_7_x86_64'
    roles:
      - split_pe_conf
      - pe-forward-console
      - pe-memory-tuning2
      - el-stop-firewall
      - el-fix-path
      - medium-size
      - base

  - name: pe-postgres-node
    hostname: pe-postgres-node.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-7-x86_64'
      - type: openstack
        volume_boot:
          image: 'centos_7_x86_64'
    roles:
      - split_pe_conf
      - pe-forward-console
      - pe-memory-tuning2
      - el-stop-firewall
      - el-fix-path
      - medium-size
      - base

  - name: split-console
    hostname: split-console.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-7-x86_64'
      - type: openstack
        volume_boot:
          image: 'centos_7_x86_64'
    roles:
      - split_pe_conf
      - pe-forward-console
      - pe-memory-tuning2
      - el-stop-firewall
      - el-fix-path
      - medium-size
      - base

  - name: split-puppetdb
    hostname: split-puppetdb.puppetdebug.vlan
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-7-x86_64'
      - type: openstack
        volume_boot:
          image: 'centos_7_x86_64'
    roles:
      - split_pe_conf
      - pe-forward-console
      - pe-memory-tuning2
      - el-stop-firewall
      - el-fix-path
      - medium-size
      - base

#  - name: pdb-sync-pe-postgres-node
#    hostname: pdb-sync-pe-postgres-node.puppetdebug.vlan
#    box: puppetlabs/centos-6.6-64-nocm
#    roles:
#      - pdb_sync_pe_conf
#      - pe-forward-console
#      - pe-memory-tuning2
#      - el-stop-firewall
#      - el-fix-path
#      - medium-size
#      - base

#  - name: pdb-sync
#    hostname: pdb-sync.puppetdebug.vlan
#    box: puppetlabs/centos-6.6-64-nocm
#    roles:
#      - pdb_sync_pe_conf
#      - pe-forward-console
#      - pe-memory-tuning2
#      - el-stop-firewall
#      - el-fix-path
#      - medium-size
#      - base

#  - name: pe-agent
#    box: puppetlabs/centos-6.6-64-nocm
#    roles:
#      - agent
#      - el-stop-firewall
#      - el-fix-path
#      - base

# vim: set ft=yaml:
